// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ad_camp/models/hive_adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignAdapter());
    registerAdapter(CampaignsListModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignAdapter());
    registerAdapter(CampaignsListModelAdapter());
  }
}
